### ISSUE TITLE
How to close SearchPage

### ISSUE THREAD

**Issue by mammba01012018** [jesusrp98/search_page#12]
Basically just want to know how to close the Search Page programmatically or any other way to close the view. I have a list and I want to close the view once selected item is tap.

**Comment by jesusrp98** [comment]
Hey @mammba01012018 ! You can close the `SearchPage` view with a simple `Navigator.of(context).pop()`, since it's a regular widget on top of the navigation tree.

You can learn more about SearchDelegate in Flutter [here](https://api.flutter.dev/flutter/material/SearchDelegate-class.html).
