### ISSUE TITLE
How to rebuild the search page

### ISSUE THREAD

**Issue by boymustafa** [jesusrp98/search_page#14]
hi,

First I would like to say thanks for this amazing package, it helps me a lot in creating a search page.  :)

There's one doubt that I need to ask. 
 So here is the use case:
1. user goes to the list of items page, on this page, an item will have the follow/unfollow button. If the user press follows button the text will be changed from "follow" to "following". It's handled perfectly by calling the setState.
2. user does a search by using the search page.
3. in the search page, when there's found item, the app will show the item like step No. 1. an item will have the follow/unfollow button, supposedly if the user press follows button the text will be changed from "follow" to "following", but it didn't happen in the search page. 

I have called setState in the search page, but doesn't work. I have tried to wrap the builder for search page into StatefulBuilder and then called setState, but still didn't work. Is there any way to refresh the search page?

**Comment by jesusrp98** [comment]
I've done some research, and I think that behaviour is not possible with the current `SearchDelegate` implementation on Flutter.

The way this feature internally inside the Flutter framework is super super restrictive, and I'm thinking about creating a new package from the ground up that allows more customisation, as well as an easier state management implementation in the search page.

**Comment by burhanaksendir** [comment]
> hi,
> 
> First I would like to say thanks for this amazing package, it helps me a lot in creating a search page. :)
> 
> There's one doubt that I need to ask. So here is the use case:
> 
> 1. user goes to the list of items page, on this page, an item will have the follow/unfollow button. If the user press follows button the text will be changed from "follow" to "following". It's handled perfectly by calling the setState.
> 2. user does a search by using the search page.
> 3. in the search page, when there's found item, the app will show the item like step No. 1. an item will have the follow/unfollow button, supposedly if the user press follows button the text will be changed from "follow" to "following", but it didn't happen in the search page.
> 
> I have called setState in the search page, but doesn't work. I have tried to wrap the builder for search page into StatefulBuilder and then called setState, but still didn't work. Is there any way to refresh the search page?

Hi @boymustafa 
Did you find a solution for this? If you found it, I would appreciate it if you could share it.

**Comment by byna11sina11** [comment]
Using StatefulBuilder is a solution
```
builder: (item) {
           return  StatefulBuilder(
             builder: (BuildContext context, StateSetter searchsetState) { ....
```

**Comment by stephenjen** [comment]
> Using StatefulBuilder is a solution
> 
> ```
> builder: (item) {
>            return  StatefulBuilder(
>              builder: (BuildContext context, StateSetter searchsetState) { ....
> ```

Thanks @byna11sina11 !
