### ISSUE TITLE
Initially displaying all items instead of placeholder

### ISSUE THREAD

**Issue by obrunsmann** [jesusrp98/search_page#2]
I would appreciate if there might be a solution to display all items from `items` field instead of the static `suggestion`.

**Comment by obrunsmann** [comment]
I am just thinking about replacing the `suggestion` Widget with a `suggetionBuilder` which gets access to the List of items.
Alternatively to gain backwards compatibility it might be possible as well to make either the suggestionBuilder or the suggestion optional and check which one has been set in the Constructor.

Edit:
Yet an other way might be to add a `bool showEmpty` flag to the Widget and do something like this:

```
    return cleanQuery.isEmpty && showEmpty == false
        ? suggestion
        : result.isEmpty
            ? failure
            : ListView(children: result.map(builder).toList());
```

I just tried this solution and I really like it :grin:

**Comment by jesusrp98** [comment]
Nice feature! Already anwsered in #3.

About the 'suggestionBuilder' parameter, do you think it will be useful for all the user of this package? How this would benefit you?

**Comment by obrunsmann** [comment]
I think the suggestionBuilder might be way too complex.. My only requirement was to give our users the chance to explore all the items if they do not actually know what to search for.

So I prefer just a simple flag.

**Comment by jesusrp98** [comment]
Thank you very mcuh for the feedback @obrunsmann . I think I would not add the `suggestionBuilder` at this moment, but I may in the future.

If you have further feedback let me know!

**Comment by obrunsmann** [comment]
I agree!
