### ISSUE TITLE
Change color

### ISSUE THREAD

**Issue by DavidGonzalezGaliana** [jesusrp98/search_page#21]
Hi, sorry for stupid issue but, is possible change the background color whiz barThelme? I am refer a search bar color

**Comment by berkeenes** [comment]
You can change the app bar color with ThemeData. 
`          barTheme: ThemeData(
              primaryIconTheme: IconThemeData(color: Colors.black),
              appBarTheme: AppBarTheme(
                  color: Colors.white,
                  iconTheme: IconThemeData(color: Colors.black))),`
