### ISSUE TITLE
Prioritize exact search results

### ISSUE THREAD

**Issue by tiennguyen9988** [jesusrp98/search_page#24]
![Screenshot_20220725_100751](https://user-images.githubusercontent.com/3782474/180691541-f6a60cd6-bf6f-4890-bbcc-0247b53ba771.png)
How to prioritize the exact search results to the top ?
Thanks!

**Comment by jesusrp98** [comment]
In order to implement this feature, I can implement the ability to sort the result list via a callback parameter, or just implementing the `Comparable` class directly inside the sorted class.

I'm going to take a look at implementing this in the next couple days.

**Comment by jesusrp98** [comment]
Implemented in the latest 2.2.0 version :)
