### ISSUE TITLE
Not working in profile mode

### ISSUE THREAD

**Issue by shuchitajain** [jesusrp98/search_page#4]
It's working fine in debug mode but when I run my app using flutter run --profile, the search page shows a gray screen instead of the results and the error is 'Another exception was thrown: Instance of 'ErrorSummary'.
Please fix it.

**Comment by jesusrp98** [comment]
That's weird. I'd need more details in order to identify the issue.

**Comment by jesusrp98** [comment]
Closed due to inactivity.
