### ISSUE TITLE
Any way to access the query in appBar?

### ISSUE THREAD

**Issue by quaintdev** [jesusrp98/search_page#7]
I need to be able to access the query that user has typed on failure so that I can do additional operations on the same. Is there a way to do the same?

**Comment by jesusrp98** [comment]
This can be easily implemented, for example.
```
onFilterUpdate: (query) => print(query)
```

What do you think?

**Comment by quaintdev** [comment]
Yes this works for me.  It's actually what I had in mind.

I got around it temporarily by making delegate.query as a class variable and referencing that variable from inside failure. It's kind of hack but I am gonna have to keep it until something like what you suggested is available.

**Comment by jesusrp98** [comment]
Hey @quaintdev , I found a solution for this feature that I'm implementing at this moment.

The only down side is that the `onQueryUpdate` function would be called also at the beginning, right after the app shows the search screen.

You can see the implementation inside the ` feature/on-query-update` branch.

Is it OK for you? This API doesn't allow me to do anything else unfortunately :(

**Comment by quaintdev** [comment]
I saw your implementation. It works for me. I can work around the limitation.

**Comment by jesusrp98** [comment]
v1.4.0 already published containing this feature!
