### ISSUE TITLE
How to change colors?

### ISSUE THREAD

**Issue by MustafaAdam** [jesusrp98/search_page#9]
How to change to search bar color?
Also, how to change the results body color?

PS: This made implementing this feature so simple and easy. Thank you for this lovely package.

**Comment by pconradjunior** [comment]
Hey, I had a problem related to colors when I upgraded my app to Flutter 2.0.0. Is there any chance to get an upgraded version of your package for use with Flutter 2?

Thank you for your awesome package!

**Comment by jesusrp98** [comment]
Hey @MustafaAdam, you can use the `barTheme` parameter inside the `SearchPage` widget to change the theme of the whole search view. You can try changing the `primaryColor` parameter of that `ThemeData` object. This change will be reflected on the actual search bar!

**Comment by jesusrp98** [comment]
@MustafaAdam this has been fixed with the latest `1.4.0+1` release, there were some issues with Flutter 2 that are fixed now.

Also planning to migrate this package to sound null safety soon!

**Comment by MustafaAdam** [comment]
Thank you for responding. The primary color changes the color of the search bar itself. Good.
But how to change the color of the body of the page?

**Comment by MustafaAdam** [comment]
I think I got.
I changed to "scaffoldBackgroundColor: Colors.white," and now it it looks good.
